app:
  name: FileBackup
  monitor:
    source-path: /Users/zhangyun/test/source
    target-path: /Users/zhangyun/test/target
    interval: 3000

server:
  port: 8081

logging:
  config: /Users/zhangyun/Documents/javaProject/FileBackup/src/main/resources/logback-spring.xml
  level:
    com.zhangyun.tools.filebackup: info
